# Nome do workflow (aparece na aba Actions do GitHub)
name: GitHub Actions Demo

# Nome da execuÃ§Ã£o (run), pode usar variÃ¡veis do GitHub
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

# Evento que dispara o workflow
# Aqui: toda vez que houver um push
on: [push]

jobs:
  # Nome do job (vocÃª escolhe)
  Explore-GitHub-Actions:

    # Sistema operacional da mÃ¡quina que o GitHub vai usar
    runs-on: ubuntu-latest

    steps:
      # Executa um comando no terminal da mÃ¡quina virtual
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."

      # Mostra o sistema operacional do runner
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      # Exibe a branch e o repositÃ³rio atual
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # Step nomeado que faz o checkout do cÃ³digo do repositÃ³rio
      - name: Check out repository code
        uses: actions/checkout@v5

      # Confirma que o repositÃ³rio foi clonado
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

      # Indica que o ambiente estÃ¡ pronto para testes
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      # Lista os arquivos do repositÃ³rio no runner
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # Mostra o status final do job
      - run: echo "ğŸ This job's status is ${{ job.status }}."
